import { expect, test } from '@playwright/test'

test('agent decision → decide → patch → recorded; owner decision → decisions.md; readiness follows', async ({ page }) => {
  await page.goto('/?t=e2e')
  await page.getByRole('button', { name: /add-decision-flow/ }).click()
  const first = page.locator('article.scn', { hasText: "The founder's reply resolves a waiting thread" })
  await first.getByRole('button', { name: /The founder's reply resolves a waiting thread/ }).click()
  await first.getByRole('button', { name: 'Ask the agent' }).click()
  await page.getByLabel('Question').fill('Partial counts?')
  await page.getByRole('button', { name: 'Send' }).click()

  const thread = page.getByRole('complementary', { name: 'Thread' })
  await expect(thread.getByText('Do partial days count toward the age?')).toBeVisible({ timeout: 20_000 })
  await expect(page.locator('.gate')).toContainText('1 · 1 blocking')
  await expect(page.locator('.gatebar small')).toContainText('1 blocking decision open')
  await expect(first.getByRole('button', { name: 'decision open' })).toBeVisible()

  await expect(thread.getByRole('radio', { name: /Count partial days/ })).toBeChecked()
  await thread.getByLabel('Note (optional)').fill('Business days only.')
  await thread.getByRole('button', { name: 'Decide' }).click()
  await expect(thread.getByText(/Decided: Count partial days/)).toBeVisible()
  await expect(thread.getByText('Recorded the decision above the scenario.')).toBeVisible({ timeout: 20_000 })
  await thread.getByRole('button', { name: 'Apply & commit' }).click()
  await expect(thread.getByText(/recorded by patch · [0-9a-f]{7}/)).toBeVisible()
  await expect(page.locator('.gatebar small')).not.toContainText('blocking decision')

  await page.getByRole('tab', { name: /Decisions/ }).click()
  await page.getByRole('button', { name: '+ Open decision' }).click()
  await page.getByLabel('Decision question').fill('Ship behind a flag?')
  await page.getByRole('button', { name: 'Save decision' }).click()
  const card = page.locator('.tabpanel .dcard', { hasText: 'Ship behind a flag?' })
  await expect(page.locator('.gatebar small')).toContainText('1 blocking decision open')
  await card.getByLabel('Your decision').fill('Yes, behind a flag.')
  await card.getByRole('button', { name: 'Decide' }).click()
  await page.getByRole('button', { name: 'All', exact: true }).click()
  await expect(card).toContainText(/recorded in decisions\.md · [0-9a-f]{7}/)
  await expect(page.locator('.dlog')).toContainText('Ship behind a flag?')
  await expect(page.locator('.dlog')).toContainText('partial days count as business days only.')
  await expect(page.locator('.gatebar small')).not.toContainText('blocking decision')
})
