import { expect, test } from '@playwright/test'
import { newInitiative } from './helpers.ts'

// Desk fixes item 2: the brief is edited on the Brief tab (Edit / Save / Cancel) and committed.
test('the brief is edited on the Brief tab, saved and committed; Cancel discards', async ({ page }) => {
  const id = await newInitiative(page, 'brief-edit')
  await page.getByRole('tab', { name: 'Brief' }).click()
  await page.getByRole('button', { name: 'Edit brief' }).click()
  const editor = page.getByLabel('Brief text')
  const text = ['# What', '', 'The **edited** brief.', '', ...Array.from({ length: 14 }, (_, i) => `- point ${i + 1}`)].join('\n')
  await editor.fill(text)
  // The editor grows with its text: every line is visible without scrolling inside it.
  expect(await editor.evaluate((el) => el.scrollHeight <= el.clientHeight + 4)).toBe(true)
  await page.getByRole('button', { name: 'Save brief' }).click()
  const shown = page.getByLabel('brief.md')
  await expect(shown.locator('strong')).toHaveText('edited')
  await expect(shown).toContainText('point 14')

  const saved = await (await page.request.get(`/api/initiatives/${id.wt}/${id.name}`)).json()
  expect(saved.brief).toBe(`${text}\n`)
  expect(saved.uncommitted).toBe(false)

  await page.getByRole('button', { name: 'Edit brief' }).click()
  await expect(page.getByLabel('Brief text')).toHaveValue(`${text}\n`)
  await page.getByLabel('Brief text').fill('Throw this away.')
  await page.getByRole('button', { name: 'Cancel' }).click()
  await expect(shown.locator('strong')).toHaveText('edited')
  expect((await (await page.request.get(`/api/initiatives/${id.wt}/${id.name}`)).json()).brief).toBe(`${text}\n`)
})

// Desk fixes item 4: inputs and research drafts open in a viewer on the initiative screen.
test('a research draft opens in the viewer with Accept/Discard; inputs open as text or inline PDF', async ({ page }) => {
  const id = await newInitiative(page, 'viewer')
  await page.getByRole('tab', { name: /Research/ }).click()
  await page.getByLabel('Research topic').fill('AR ageing')
  await page.getByLabel('Research questions').fill('Which report?')
  await page.getByRole('button', { name: 'Research', exact: true }).click()
  const draft = page.getByRole('button', { name: 'research-ar-ageing.md' })
  await expect(draft).toBeVisible({ timeout: 20_000 })
  await draft.click()
  const viewer = page.getByRole('region', { name: 'research-ar-ageing.md' })
  await expect(viewer.locator('strong')).toHaveText('aged receivables')
  await expect(viewer).toContainText('https://developer.intuit.com/')
  await viewer.getByRole('button', { name: 'Accept' }).click()
  await expect(page.getByRole('status')).toHaveText('research-ar-ageing.md accepted and committed')
  await expect(viewer.getByRole('button', { name: 'Accept' })).toHaveCount(0)
  await viewer.getByRole('button', { name: 'Close' }).click()
  await expect(viewer).toHaveCount(0)

  await page.getByRole('tab', { name: /Inputs/ }).click()
  await page.getByLabel('Add from repo (path relative to the hub)').fill('config.yaml')
  await page.getByRole('button', { name: 'Add', exact: true }).click()
  await page.locator('#upload-inputs').setInputFiles({ name: 'spec.pdf', mimeType: 'application/pdf', buffer: Buffer.from('%PDF-1.4\n%%EOF\n') })
  await page.getByRole('button', { name: 'Upload', exact: true }).click()
  await page.getByRole('button', { name: 'config.yaml' }).click()
  const yaml = page.getByRole('region', { name: 'config.yaml' })
  await expect(yaml.locator('pre')).toContainText('initiativeBase: initiative-base')
  await yaml.getByRole('button', { name: 'Close' }).click()
  await page.getByRole('button', { name: 'spec.pdf' }).click()
  const frame = page.getByRole('region', { name: 'spec.pdf' }).locator('iframe')
  await expect(frame).toHaveAttribute('src', `/api/initiatives/${id.wt}/${id.name}/inputs/spec.pdf`)
  const pdf = await page.request.get(`/api/initiatives/${id.wt}/${id.name}/inputs/spec.pdf`)
  expect(pdf.headers()['content-type']).toBe('application/pdf')
  expect(pdf.headers()['content-disposition']).toBe('inline; filename="spec.pdf"')
})
